config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'twitter_apps/history'

  resources :search_histories

  get 'twitter_apps/(:id)' => 'twitter_apps#index', as: :twitter_apps

  get 'tweets_as_json/(:id)', to: 'twitter_apps#get_tweets', as: :get_tweets

  root to: 'twitter_apps#index'

end

app/models/city.rb
#http://railscasts.com/episodes/273-geocoder
class City 
	# extend Geocoder::Model::ActiveRecord
	# 	# http://www.rubygeocoder.com/
	# geocoded_by :address
	# reverse_geocoded_by :latitude, :longitude
	# after_validation :geocode, :reverse_geocode
	
	##model without DB
	#http://stackoverflow.com/questions/14389105/rails-model-without-a-table
	# include ActiveModel::Validations
	# include ActiveModel::Conversion
	# extend ActiveModel::Naming

	##addedd attr_accessor
	attr_accessor :address, :latitude, :longitude, :name
	

	
end

app/models/location_tweet.rb
class Location_Tweet
	##model without DB
	#http://stackoverflow.com/questions/14389105/rails-model-without-a-table
	# include ActiveModel::Validations
	# include ActiveModel::Conversion
	# extend ActiveModel::Naming

	attr_accessor :message, :latitute, :longitude, :address, :num_retweets, :date_time, :image_url

	def initialize(msg, lat, lon, address, num_retweets, date_time, img_url)
		self.message = msg
		self.latitute = lat
		self.longitude = lon
		self.address = address
		self.num_retweets = num_retweets
		self.date_time = date_time
		self.image_url = img_url
	end

	def getAddress
		# use geocoder to get address
		s = Geocoder.search("#{self.latitute}, #{self.longitude}")
        self.address = s[0].address
	end
	# def persisted?
	# 	false
	# end

end

app/models/search_history.rb
class SearchHistory < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :search_history 	##the manager

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/location_tweets_controller.rb
class LocationTweetsController < ApplicationController

	# def get_tweets
	# 	#@twitter_streaming_client = Twitter::Streaming::Client.new(TWITTER_CONFIG)
	# 	@twitter_rest_client = Twitter::REST::Client.new(TWITTER_CONFIG)		
	# binding.pry
	# 	@twitter_rest_client.search(@topics, result_type: "recent", geocode: "#{@my_city.latitude },#{@my_city.longitude },#{@radius}mi").take(100).each do |tweet|

 #  			if (tweet.geo?) then
 #  				# everse engineer the address from the lat lon. This will quickly exceed geocoder limit. Better to do so if user requests it
 #  				#s = Geocoder.search("#{tweet.geo.lat}, #{tweet.geo.long}")
 #  				#puts s[0].address
	# 			@arr_tweets<< Location_Tweet.new(tweet.text, tweet.geo.lat.to_f, tweet.geo.long.to_f, \
	# 				"address tbd", tweet.retweeted? ? tweet.retweet_count : 0, tweet.created_at.to_datetime, tweet.media? ? tweet.media[0].media_url.to_s : "")
	# 		end
	# 	end
	# 	#@twitter_display = @arr_tweets

	# 	puts "done initializing\n\n\n\n\n\n\n\n"

	# 	render :json => @arr_tweets

	# end
end

app/controllers/search_histories_controller.rb
class SearchHistoriesController < ApplicationController
	before_action :authenticate_user!

	def index
		# tabular view of search history and ability to start new search from here
		@search_histories = SearchHistory.where(user_id: current_user.id).sort_by { |h| h[:updated_at]}.reverse!
	end

	def destroy
		@history = SearchHistory.find_by_id(params[:id])
		if !@history.nil? then
			@history.destroy
		flash[:notice] = "Entry deleted" 
		end
		redirect_to :back
	end
end

app/controllers/twitter_apps_controller.rb
class TwitterAppsController < ApplicationController
  def index

    # SET DEFAULT VALUES FOR FIRST RUN
    @from_date = params[:from]
    @to_date = params[:to]

    @radius = params[:radius]

    # binding.pry
    if @radius == nil || @radius == "" then 
      signed_in? && !@search_histories.nil? ? @radius = @search_histories.last.radius : @radius = "400"
    end

    @topics = params[:keyword]
    #@city_name = params[:loc]
    if @topics == nil
      signed_in? && !@search_histories.nil? ? @topics = @search_histories.last.searchstring : @topics = "earthquake -USGS OR flood"
    end

    if @from_date!="" && @from_date!=nil then
      @topics = @topics + " since:" + @from_date 
    end

    if @to_date!="" && @to_date!=nil then 
      @topics = @topics + " until:" + @to_date
    end

    @city_to_lookup = params[:address]
    # binding.pry
    if @city_to_lookup == nil 
      signed_in? && !@search_histories.nil? ? @city_to_lookup = @search_histories.last.address : @city_to_lookup = "San Francisco, CA" 
    end

    @city_found = true
    #use geocoder to add city
    #@my_city = City.new({ :address => @city_to_lookup })
    s = Geocoder.search("#{@city_to_lookup}")
    #binding.pry
    if s.count > 0 then
      #create a new city
      c = City.new
      c.latitude = s[0].latitude
      c.longitude = s[0].longitude
      c.address = s[0].formatted_address
      c.name = @city_to_lookup
      @my_city = c
    else
      @city_found = false
    end

    #if user is logged in: save search history
    if signed_in? then
      # see if search history exists already
      h = SearchHistory.where(searchstring: @topics, address: @city_to_lookup, radius: @radius, user: current_user)
      # binding.pry
      if h[0].nil? then
        h = SearchHistory.new
        h.searchstring = @topics
        h.address = @city_to_lookup
        h.radius = @radius
        h.user = current_user
        h.save
      end
    end

  end

  def get_tweets
    @arr_tweets = []

    # grab incoming params
    @topics = params[:topic]
    @lat = params[:lat]
    @lon = params[:lon]
    @radius = params[:radius]
    @city_to_lookup = params[:city]

    ##initLocation is used to center the map (and specify zoom level based on radius)
    initLocation = Location_Tweet.new("",@lat,@lon,"",@radius,"","")
    @arr_tweets<<initLocation

    #@twitter_streaming_client = Twitter::Streaming::Client.new(TWITTER_CONFIG)
    @twitter_rest_client = Twitter::REST::Client.new(TWITTER_CONFIG)    

    @twitter_rest_client.search(@topics, result_type: "recent", geocode: "#{@lat },#{@lon},#{@radius}mi").take(100).each do |tweet|

        if (tweet.geo?) then
          # reverse engineer the address from the lat lon. This will quickly exceed geocoder limit. Better to do so if user requests it
          #s = Geocoder.search("#{tweet.geo.lat}, #{tweet.geo.long}")
          #puts s[0].address


        @arr_tweets<< Location_Tweet.new(tweet.text, tweet.geo.lat.to_f, tweet.geo.long.to_f, \
          "address tbd", tweet.retweeted? ? tweet.retweet_count : 0, tweet.created_at.to_datetime.strftime('%m/%d | %R'), tweet.media? ? tweet.media[0].media_url.to_s : "")
      end
    end
    #@twitter_display = @arr_tweets

    # add result stats to history
    if signed_in? then
      h = SearchHistory.where(searchstring: @topics, address: @city_to_lookup, radius: @radius, user: current_user)

      h[0].num_results = @arr_tweets.size - 1
      # h.num_images = @arr_tweets.select {|a| a.image_url != ""}.count
      h[0].save
      puts "saved tweet count to search history: #{@arr_tweets.size - 1}"
    end
    @arr_tweets.sort_by { |h| h.date_time}
    render :json => @arr_tweets#.sort_by { |h| h.date_time}.reverse!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_tweets_helper.rb
module LocationTweetsHelper
end

app/helpers/search_histories_helper.rb
module SearchHistoriesHelper
end

app/helpers/twitter_apps_helper.rb
module TwitterAppsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TT Twitter Map</title>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap-theme.css">
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <ul class="nav">
  <li class="active"><a href="/search_histories">Search History</a></li>
</ul> -->

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to 'My Search History',search_histories_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
	
<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    <a href="http://www.thorntontomasetti.com" target="_blank">Thornton Tomasetti </a> <a href="http://core.thorntontomasetti.com" target="_blank">CORE studio</a> 2015
  </div>
</footer>
</body>
</html>

app/views/search_histories/destroy.html.erb
<h1>Destroy Search History</h1>

this page is not in use

app/views/search_histories/index.html.erb
<h1>My Search History</h1>

<table>
	<thead>
		<tr>
			<td style="padding:0 10px 0 10px;">Last Search Date</td>
		<td style="padding:0 10px 0 10px;">Search Term</td>
		<td style="padding:0 10px 0 10px;">Address</td>
		<td style="padding:0 10px 0 10px;">Radius</td>
		<td style="padding:0 10px 0 10px;"># Results</td>
		<td style="padding:0 10px 0 10px;">Repeat Search</td>
	</tr>
	</thead>

	<tbody>
		<%@search_histories.each do |h| %>
			<tr>
				<td style="padding:0 10px 0 10px;"><%= h.updated_at%></td>
				<td style="padding:0 10px 0 10px;"><%= h.searchstring%></td>
				<td style="padding:0 10px 0 10px;"><%= h.address%></td>
				<td style="padding:0 10px 0 10px;"><%= h.radius%></td>
				<td style="padding:0 10px 0 10px;"><%= h.num_results%></td>
				<td style="padding:0 10px 0 10px;"><%= link_to "Search This", twitter_apps_path(:keyword => h.searchstring, :address => h.address, :radius => h.radius)%></td>
				<td style="padding:0 10px 0 10px;"><%= link_to "Delete Entry", h, method: :delete, data: {confirm: "Are you sure?"}%></td>
			</tr>
		<% end %>
	</tbody>
</table>

<p></p>
<p><%= link_to "Back to Main Page", twitter_apps_path %></p>

app/views/twitter_apps/history.html.erb
<h1>TwitterApps#history</h1>
<p>Find me in app/views/twitter_apps/history.html.erb</p>

app/views/twitter_apps/index.html.erb
<!-- <script type="text/javascript" src="/assets/utilities.js"></script> -->
<h1> What and Where?</h1>

<!--search field form to feed twitter_apps:-->
<form action= 'twitter_apps' method='GET' >
	<fieldset id = 'input-fieldset'>
    <div>
     Search Phrase:
     <input type="text" value='<%="#{@topics}"%>' name="keyword" style="width:350px;">
    </div>
    <p>query options: "exact phrase", flood OR damage (containing either flood or damage), flood damage (containing both flood and damage), <a href="https://dev.twitter.com/rest/public/search" target="_blank">more</a> </p>
    <div>
  	Address to search:
  	<input type="text" value='<%="#{@city_to_lookup}"%>' name="address" >
  	</div>
    
    <div>
      Search Radius:
      <span id="slider"></span>
      <script>

        $(function() {
          $( "#slider" ).slider({
            value: <%="#{@radius}"%>,
            min: 10,
            max: 2000,
            step: 10,
            slide: function( event, ui ) {
              $( "#radius" ).val(ui.value);
            }
          });

          $( "#radius" ).val( $( "#slider" ).slider( "value" ));
        });
      </script>
      <input type="number" value'<%="#{@radius}"%> miles' id="radius" name="radius" maxlength="10" readonly style="border:0;  width:65px;">
    </div>

    <div>
      Optional Date Range:
      <class="texthover" title="Twitter only allows for searches up to 7 days ago." ><label for="from">from</label>
      <input type="text" id="from" name="from">
      <label for="to">to</label>
      <input type="text" id="to" name="to">
      <script>
      $(function() {
        $( "#from" ).datepicker({
          dateFormat: "yy-mm-dd",
          minDate: '-7d',
          maxDate: '-1d',
          defaultDate: "-1d",
          changeMonth: true,
          numberOfMonths: 2,
          onClose: function( selectedDate ) {
            $( "#to" ).datepicker("option", "minDate", (selectedDate > defaultDate ? '0' : selectedDate));
          },
        });
        $( "#to" ).datepicker({
          dateFormat: "yy-mm-dd",
          defaultDate: "0",
          minDate: '-6d',
          maxDate: '0',
          changeMonth: true,
          numberOfMonths: 2,
          onClose: function( selectedDate ) {
            //$( "#from" ).datepicker( "option", "maxDate", (selectedDate > defaultDate ? '-1d' : selectedDate) );
            $( "#from" ).datepicker( "option", "maxDate", selectedDate);
          }
        });

        // $("#slider").slider({ 
        //  min: 10,
        //  max: 2000,
        //  step: 10,
        //  //value: gon.radius
        //  //value: 100
        // });
      });           

      </script>
      <br>
      <input type="submit" value="Submit">
    </div>
  </fieldset>
</form>

<div id="map-container">
  <div id="map-canvas"></div>
</div>

<div id="image-reel"></div>

<div id ="table" style="height:200px;overflow:auto;width:100%">
  <!--<table id="tweets-table" class = "sortable">-->
  <table id="tweets-table" class = "sortable">
    <thead id = "table-head">
      <tr>
        <th WIDTH = "3%"></th>
        <th WIDTH = "8%">Date | Time</th>
        <th WIDTH = "7%">Location</th>
        <th WIDTH = "14%">Address</th>
        <th WIDTH = "68%">Tweet Message</th>
        <th colspan="20"></th>
      </tr>
    </thead>
    <tbody id = "table-body">
    </tbody>
  </table>
</div>

<script type="text/javascript">
var twitterResponse = [];
<%# binding.pry %>
<%#//= link_to 'Send Thanks', new_invoice_email_path(@invoice, :type => "thanks") %>
$.getJSON('<%= get_tweets_path(:lat => @my_city.latitude, :lon => @my_city.longitude,
 :topic => @topics, :radius => @radius, :city => @my_city.name) %>', function(data) // Variable data contains the data we get from serverside
{
  twitterResponse = data;

  if(twitterResponse.count <2){
    alert("No tweets found!");
  }
  else
  {
    var script = document.createElement('script');
    script.type = 'text/javascript';

    //call initializeMap here
    script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp&' + 'libraries=places,visualization&'+'callback=initializeMap';
    document.body.appendChild(script);

    // //TODO: populate image reel div

    var imgReel = document.getElementById('image-reel');

    var tableBody = document.getElementById('table-body');

    for(i = 1; i < twitterResponse.length; i++)
    {
      //collect images
      if(twitterResponse[i].image_url.toString()!="")
      {
        //imgReel.append('<div class="image"><img src="' + twitterResponse[i].image_url + '""></img></div>');
        var elem = document.createElement("img");
        elem.src = twitterResponse[i].image_url;
        elem.className = "image";
        imgReel.appendChild(elem);
      }

      //build table with tweet info. Use two-color scheme
      var tr = document.createElement('TR');
      if(i % 2 == 0){ tr.className = "even";}
      else{ tr.className = "odd"; }

        var td = document.createElement('TD');
        //checkbox
        var box = document.createElement("INPUT");
        box.setAttribute("type", "checkbox");
        box.id = "checkbox_" + i.toString();
        td.appendChild(box);
        // td.appendChild(document.createTextNode(i.toString()));
        tr.appendChild(td);
        
        //Date/Time
        td = document.createElement('TD');
        td.appendChild(document.createTextNode(twitterResponse[i].date_time));
        tr.appendChild(td);

        //Location
        var link = document.createElement("A");
        link.setAttribute('href','http://maps.google.com/?q=' + twitterResponse[i].latitute+ ',' + twitterResponse[i].longitude);
        link.setAttribute('target','_blank')
        link.text='open map'; 
        td = document.createElement('TD');
        td.appendChild(link);
        tr.appendChild(td);
        //Longitude 
        td = document.createElement('TD');
        td.appendChild(document.createTextNode(twitterResponse[i].latitute+','+twitterResponse[i].longitude));
        tr.appendChild(td);
        // td = document.createElement('TD');
        // tr.appendChild(td);
      
        //message 
        td = document.createElement('TD');        
        td.appendChild(document.createTextNode(twitterResponse[i].message));

        //image link 
        if(twitterResponse[i].image_url.toString()!="")
        {
          var imageLink = document.createElement("A");
          imageLink.setAttribute('href', twitterResponse[i].image_url.toString());
          imageLink.setAttribute('target', '_blank');
          imageLink.text = ' : view image';
          td.appendChild(imageLink);
        }
        tr.appendChild(td);

        tableBody.appendChild(tr);
      } 
    }
  }); //end of twitterResponse collection


  </script>